services:
  receiver:
    build: .
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - proxy-network

  influxdb:
    image: docker.io/library/influxdb:2.7-alpine
    env_file:
      - .env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - proxy-network

volumes:
  influxdb-data:

networks:
  proxy-network:
    external: true
